export const SKIP_META_KEYS = new Set([
  "category",
  "status",
  "confidence",
  "completeness_score",
  "raw_content",
  "source_entry_id",
  "full_text",
  "workspace",
  "enrichment",
  "ai_insight",
  "ai_insight_short",
  "merge_note",
  "audit_flags",
]);
