// ─────────────────────────────────────────────────────────────────────────────
// mergeEntries — shared core for the /api/entries?action=merge web flow,
// the MCP merge_entries tool, the chat merge_entries tool, and the
// /v1/merge public REST endpoint. Everything that touches the merge
// pipeline (LLM prompt, markdown sanitiser, metadata inheritance, quota
// peek, audit-log write, source soft-delete) lives here so the four
// surfaces can't drift.
//
// The web flow is a two-phase preview/commit (user reviews and edits the
// LLM output before committing). The non-interactive flows are one-shot
// (generate + commit in one call) — see mergeEntriesOneShot.
// ─────────────────────────────────────────────────────────────────────────────

import { randomUUID } from "crypto";
import { ApiError, requireBrainAccess } from "./withAuth.js";
import { sbHeaders, sbHeadersNoContent } from "./sbHeaders.js";
import { callAI } from "./aiProvider.js";
import { resolveProviderForUser } from "./resolveProvider.js";
import { SERVER_PROMPTS } from "./prompts.js";
import { dailyLimitForTier, fetchUserTier, readQuotaUsage } from "./enrichQuota.js";
import { enrichInline } from "./enrich.js";

const SB_URL = (process.env.SUPABASE_URL || "").trim();

const ENTRY_FIELDS =
  "id,title,content,type,tags,metadata,brain_id,importance,pinned,created_at,embedded_at,embedding_status,status";

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// Internal/AI-managed metadata keys — never inherit these onto the merged
// entry (they get regenerated by enrichInline) and never expose them to
// the LLM (they're noise that bloats the prompt).
const INTERNAL_META_KEYS = new Set<string>([
  "enrichment",
  "ai_summary",
  "ai_insight",
  "ai_concepts",
  "concepts",
  "concept_ids",
  "full_text",
  "raw_content",
  "attachment_text",
  "chunks",
  "embedding",
  "embedded_at",
  "embedding_status",
  "embedding_dim",
  "classifier",
  "classifier_score",
  "classifier_label",
  "auto_accept_pending",
  "skip_persona",
  "ingest_source",
  "source_message_id",
  "gmail_message_id",
  "gmail_thread_id",
  "gmail_account",
  "gmail_subject",
  "gmail_from",
  "gmail_to",
  "gmail_date",
  "gmail_attachment_ids",
  "gmail_attachment_names",
  "gmail_html",
  "gmail_text",
  "gmail_snippet",
  "extracted_at",
  "parsed_at",
  "last_skip_reason",
  "merged_from",
  "merged_at",
]);

// First-class structured fields the detail panel renders as DETAILS chips
// and that the LLM should see in the prompt source block. Used for prompt
// rendering ORDER only — any non-internal primitive on a source's metadata
// is inherited at commit time.
const PROMPT_DETAIL_KEYS = [
  "name", "contact_name", "full_name", "preferred_name", "pronouns",
  "amount", "price", "currency", "account_number", "reference_number",
  "reference", "invoice_number",
  "due_date", "deadline", "expiry_date", "renewal_date", "event_date",
  "date", "when", "time",
  "cellphone", "cell", "phone", "mobile", "landline", "fax",
  "email", "secondary_email",
  "address", "location", "where", "city", "country", "postcode", "province",
  "id_number", "national_id", "passport_number", "dob", "birthday",
  "url", "website", "link", "status", "vendor", "company", "organization",
];

// Strip markdown formatting so content survives the plain-text renderer
// (cards + DetailModal use whiteSpace:pre-wrap with no markdown parser).
// Conservative: only removes formatting markers, keeps inner text and
// list bullets / paragraph structure intact.
export function stripMarkdown(input: string): string {
  if (!input) return "";
  let s = input;
  s = s.replace(/```[a-zA-Z0-9]*\n?/g, "").replace(/```/g, "");
  s = s.replace(/`([^`\n]+)`/g, "$1");
  s = s.replace(/\*\*\*([^\n*]+)\*\*\*/g, "$1");
  s = s.replace(/___([^\n_]+)___/g, "$1");
  s = s.replace(/\*\*([^\n*]+)\*\*/g, "$1");
  s = s.replace(/__([^\n_]+)__/g, "$1");
  s = s.replace(/(^|[\s(])\*(\S[^\n*]*?\S|\S)\*(?=[\s.,;:!?)]|$)/g, "$1$2");
  s = s.replace(/(^|[\s(])_(\S[^\n_]*?\S|\S)_(?=[\s.,;:!?)]|$)/g, "$1$2");
  s = s.replace(/~~([^\n~]+)~~/g, "$1");
  s = s.replace(/^[ \t]*#{1,6}[ \t]+/gm, "");
  s = s.replace(/^[ \t]*>[ \t]?/gm, "");
  s = s.replace(/\[([^\]\n]+)\]\(([^)\n]+)\)/g, "$1 ($2)");
  s = s.replace(/<\/?[a-zA-Z][a-zA-Z0-9-]*(?:\s[^>]*)?>/g, "");
  s = s.replace(/\n{3,}/g, "\n\n");
  return s;
}

function renderSourceMeta(meta: unknown): string {
  if (!meta || typeof meta !== "object") return "";
  const m = meta as Record<string, unknown>;
  const lines: string[] = [];
  const seen = new Set<string>();
  const emit = (k: string) => {
    if (seen.has(k) || INTERNAL_META_KEYS.has(k)) return;
    const v = m[k];
    if (v == null) return;
    if (Array.isArray(v)) {
      const items = v.filter((x) => x != null && x !== "").map((x) => String(x));
      if (!items.length) return;
      lines.push(`${k}: ${items.join(", ")}`);
    } else if (typeof v === "object") {
      return; // skip nested
    } else {
      const s = String(v).trim();
      if (!s) return;
      lines.push(`${k}: ${s}`);
    }
    seen.add(k);
  };
  for (const k of PROMPT_DETAIL_KEYS) emit(k);
  for (const k of Object.keys(m)) emit(k);
  return lines.join("\n");
}

// ── Public types ─────────────────────────────────────────────────────────────

export interface MergeSourceRow {
  id: string;
  title: string;
  content: string | null;
  type: string | null;
  tags: string[] | null;
  metadata: Record<string, unknown> | null;
  brain_id: string | null;
  importance: number | null;
  pinned: boolean | null;
  created_at: string | null;
}

export interface MergeValidation {
  cleanIds: string[];
  sources: MergeSourceRow[];
  brainId: string;
}

export interface MergeFields {
  title: string;
  content: string;
  type: string;
  tags: string[];
}

export interface MergeResult {
  merged_id: string;
  merged: unknown;
  source_ids: string[];
  enrichment_pending: boolean;
}

// ── Validation ───────────────────────────────────────────────────────────────

export async function validateMergeRequest(
  userId: string,
  ids: unknown,
): Promise<MergeValidation> {
  if (!Array.isArray(ids) || ids.length < 2 || ids.length > 8) {
    throw new ApiError(400, "ids must be an array of 2-8 entry uuids");
  }
  const cleanIds: string[] = [];
  const seen = new Set<string>();
  for (const raw of ids) {
    if (typeof raw !== "string" || !UUID_RE.test(raw)) {
      throw new ApiError(400, "ids must be valid uuids");
    }
    if (seen.has(raw)) continue;
    seen.add(raw);
    cleanIds.push(raw);
  }
  if (cleanIds.length < 2) {
    throw new ApiError(400, "merge needs at least 2 distinct entries");
  }

  // Fetch sources, verify ownership + same brain + no vault. RLS would
  // already block cross-user reads but defense-in-depth.
  const idList = cleanIds.map((id) => encodeURIComponent(id)).join(",");
  const fetchRes = await fetch(
    `${SB_URL}/rest/v1/entries?id=in.(${idList})&user_id=eq.${encodeURIComponent(userId)}&deleted_at=is.null&select=${encodeURIComponent(ENTRY_FIELDS)}`,
    { headers: sbHeadersNoContent() },
  );
  if (!fetchRes.ok) {
    throw new ApiError(502, `Failed to fetch entries: HTTP ${fetchRes.status}`);
  }
  const sources = (await fetchRes.json()) as MergeSourceRow[];
  if (sources.length !== cleanIds.length) {
    throw new ApiError(404, "One or more entries not found, deleted, or not owned by you");
  }
  const vault = sources.find((s) => s.type === "secret");
  if (vault) {
    throw new ApiError(
      400,
      `Cannot merge vault entry "${vault.title}" — vault contents can't be processed by the LLM`,
    );
  }
  const brainIds = new Set(sources.map((s) => s.brain_id).filter(Boolean) as string[]);
  if (brainIds.size > 1) {
    throw new ApiError(400, "All selected entries must be in the same brain");
  }
  if (brainIds.size === 0) {
    throw new ApiError(400, "Selected entries have no brain assigned");
  }
  const brainId = [...brainIds][0]!;
  await requireBrainAccess(userId, brainId);

  return { cleanIds, sources, brainId };
}

// ── Quota peek ───────────────────────────────────────────────────────────────

export async function checkMergeQuota(userId: string): Promise<void> {
  const tier = await fetchUserTier(userId);
  const dailyLimit = dailyLimitForTier(tier);
  if (dailyLimit > 0) {
    const used = await readQuotaUsage(userId);
    if (used && used.used >= dailyLimit) {
      throw new ApiError(
        429,
        `Daily enrichment quota reached (${used.used}/${dailyLimit}). Try again tomorrow.`,
      );
    }
  }
}

// ── LLM preview ──────────────────────────────────────────────────────────────

export async function generateMergePreview(
  sources: MergeSourceRow[],
  userId: string,
): Promise<MergeFields> {
  const cfg = await resolveProviderForUser(userId).catch(() => null);
  if (!cfg) {
    throw new ApiError(503, "AI provider unavailable — try again shortly");
  }
  const sourcesBlock = sources
    .map((s, i) => {
      const tagStr = (s.tags || []).join(", ") || "(none)";
      const detailsBlock = renderSourceMeta(s.metadata);
      const detailsLine = detailsBlock ? `Details:\n${detailsBlock}` : null;
      return [
        `### Source ${i + 1}`,
        `Title: ${s.title}`,
        `Type: ${s.type ?? "note"}`,
        `Tags: ${tagStr}`,
        detailsLine,
        `Content:\n${(s.content ?? "").slice(0, 4000)}`,
      ]
        .filter(Boolean)
        .join("\n");
    })
    .join("\n\n");
  const prompt = SERVER_PROMPTS.MERGE_ENTRIES.replace("{{SOURCES}}", sourcesBlock);
  const aiRaw = await callAI(cfg, prompt, "Merge the entries above.", {
    maxTokens: 4000,
    json: true,
  });
  if (!aiRaw) {
    throw new ApiError(502, "LLM merge call returned empty — try again");
  }
  let parsed: { title?: string; content?: string; type?: string; tags?: string[] } = {};
  try {
    const cleaned = aiRaw.replace(/```(?:json)?\s*/gi, "").replace(/```/g, "");
    const match = cleaned.match(/\{[\s\S]*\}/);
    parsed = match ? JSON.parse(match[0]) : {};
  } catch {
    throw new ApiError(502, "LLM merge call returned malformed JSON");
  }
  return {
    title:
      typeof parsed.title === "string" ? stripMarkdown(parsed.title).slice(0, 200) : "Merged entry",
    content:
      typeof parsed.content === "string" ? stripMarkdown(parsed.content).slice(0, 50_000) : "",
    type:
      typeof parsed.type === "string" ? parsed.type.toLowerCase().slice(0, 50) : "note",
    tags: Array.isArray(parsed.tags)
      ? parsed.tags
          .filter((t): t is string => typeof t === "string")
          .map((t) => t.toLowerCase().slice(0, 40))
          .slice(0, 10)
      : [],
  };
}

// ── Commit ───────────────────────────────────────────────────────────────────

export interface CommitMergeOpts {
  /** User-edited (or LLM-generated) merged fields. */
  fields: MergeFields;
  /** Max ms to wait for inline enrichment. Default 60_000. The hourly
   *  cron picks up anything that misses this window. */
  enrichTimeoutMs?: number;
}

export async function commitMerge(
  userId: string,
  validation: MergeValidation,
  opts: CommitMergeOpts,
): Promise<MergeResult> {
  const { cleanIds, sources, brainId } = validation;
  const enrichTimeoutMs = opts.enrichTimeoutMs ?? 60_000;

  // Sanitize incoming fields. stripMarkdown handles user-pasted markdown
  // even if the LLM was clean. Type/secret guard mirrors handleMerge.
  const title = stripMarkdown(opts.fields.title || "").trim().slice(0, 200);
  const content = stripMarkdown(opts.fields.content || "").slice(0, 50_000);
  const type = (opts.fields.type || "note").toLowerCase().trim().slice(0, 50);
  const tags = (opts.fields.tags || [])
    .filter((t): t is string => typeof t === "string")
    .map((t) => t.toLowerCase().trim().slice(0, 40))
    .filter(Boolean)
    .slice(0, 10);

  if (!title || !content) {
    throw new ApiError(400, "title and content required for commit");
  }
  if (type === "secret") {
    throw new ApiError(
      400,
      "Cannot create a vault entry via merge — use the in-app Vault flow",
    );
  }

  // Inheritance: pinned union, importance max, tag union, newest created_at.
  const pinned = sources.some((s) => !!s.pinned);
  const importance = sources.reduce((m, s) => Math.max(m, s.importance ?? 0), 0);
  const sourceTags = sources.flatMap((s) => s.tags ?? []) as string[];
  const mergedTags = Array.from(
    new Set([...tags, ...sourceTags.map((t) => t.toLowerCase())]),
  ).slice(0, 10);
  const newestCreated = sources
    .map((s) => s.created_at)
    .filter((x): x is string => !!x)
    .sort()
    .pop();

  // Inherit structured metadata. First non-empty value wins. Skip
  // internal/AI-managed keys — those get regenerated by enrichInline.
  const inheritedMeta: Record<string, unknown> = {};
  for (const s of sources) {
    const sm = s.metadata;
    if (!sm || typeof sm !== "object") continue;
    for (const [k, v] of Object.entries(sm)) {
      if (INTERNAL_META_KEYS.has(k)) continue;
      if (k in inheritedMeta) continue;
      if (v == null) continue;
      if (Array.isArray(v)) {
        if (!v.length) continue;
        inheritedMeta[k] = v;
      } else if (typeof v === "object") {
        continue;
      } else {
        const s2 = String(v).trim();
        if (!s2) continue;
        inheritedMeta[k] = v;
      }
    }
  }

  const mergedId = (randomUUID as () => string)();
  const insertBody = {
    id: mergedId,
    user_id: userId,
    brain_id: brainId,
    title,
    content,
    type,
    tags: mergedTags,
    pinned,
    importance,
    metadata: {
      ...inheritedMeta,
      merged_from: cleanIds,
      merged_at: new Date().toISOString(),
    },
    status: "active",
    enrichment_state: "pending",
    created_at: newestCreated ?? new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };
  const insertRes = await fetch(`${SB_URL}/rest/v1/entries`, {
    method: "POST",
    headers: sbHeaders({ Prefer: "return=representation" }),
    body: JSON.stringify(insertBody),
  });
  if (!insertRes.ok) {
    const txt = await insertRes.text().catch(() => "");
    throw new ApiError(502, `Failed to insert merged entry: ${txt.slice(0, 200)}`);
  }
  const [merged] = (await insertRes.json()) as unknown[];

  // Bounded inline enrichment. If the LLM is slow we bail and let the
  // hourly cron finish the job — the row is still searchable in the
  // meantime because content + tags are populated.
  let enrichTimedOut = false;
  await Promise.race([
    enrichInline(mergedId, userId).catch((err: unknown) => {
      console.error(
        "[mergeEntries:enrichInline]",
        mergedId,
        err instanceof Error ? err.message : err,
      );
    }),
    new Promise<void>((resolve) => {
      setTimeout(() => {
        enrichTimedOut = true;
        resolve();
      }, enrichTimeoutMs);
    }),
  ]);

  // Soft-delete sources. Failure here doesn't unwind the merge — the
  // user sees both the merged entry and the originals briefly, which is
  // recoverable, vs leaving the merged row unborn.
  const idList = cleanIds.map((id) => encodeURIComponent(id)).join(",");
  await fetch(
    `${SB_URL}/rest/v1/entries?id=in.(${idList})&user_id=eq.${encodeURIComponent(userId)}`,
    {
      method: "PATCH",
      headers: sbHeaders({ Prefer: "return=minimal" }),
      body: JSON.stringify({ deleted_at: new Date().toISOString() }),
    },
  ).catch((err) => {
    console.error("[mergeEntries:soft-delete-sources]", err);
  });

  // Audit log — best-effort.
  fetch(`${SB_URL}/rest/v1/audit_log`, {
    method: "POST",
    headers: sbHeaders({ Prefer: "return=minimal" }),
    body: JSON.stringify({
      user_id: userId,
      action: "entries_merged",
      resource_id: mergedId,
      metadata: { source_ids: cleanIds, count: cleanIds.length },
      timestamp: new Date().toISOString(),
    }),
  }).catch(() => {});

  return {
    merged_id: mergedId,
    merged: merged ?? null,
    source_ids: cleanIds,
    enrichment_pending: enrichTimedOut,
  };
}

// ── One-shot orchestrator ────────────────────────────────────────────────────
//
// Used by the non-interactive surfaces (MCP, chat, /v1/merge) that don't
// have a preview/edit step. Runs validate → quota peek → LLM → commit
// in one call.
export async function mergeEntriesOneShot(
  userId: string,
  ids: unknown,
  opts?: { enrichTimeoutMs?: number },
): Promise<MergeResult> {
  const validation = await validateMergeRequest(userId, ids);
  await checkMergeQuota(userId);
  const fields = await generateMergePreview(validation.sources, userId);
  return commitMerge(userId, validation, {
    fields,
    enrichTimeoutMs: opts?.enrichTimeoutMs,
  });
}
